spring.application.name=ApiEstoque
spring.datasource.url=jdbc:postgresql://localhost:5432/dbEstoque
spring.datasource.username=postgres
spring.datasource.password=123456
spring.jpa.hibernate.ddl-auto=update
